# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AiIssue < Formula
  desc "A CLI tool to publish AI-generated ideas as GitHub Issues, clearly separating AI authorship from human responsibility."
  homepage "https://github.com/replworks/ai-issue"
  version "1.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/replworks/ai-issue/releases/download/v1.0.2/ai-issue_1.0.2_darwin_amd64.tar.gz"
      sha256 "e10ffbca83bd2a296efd01d684001f8ea2898e0048c493febc114abba56b5f9a"

      define_method(:install) do
        bin.install "ai-issue"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/replworks/ai-issue/releases/download/v1.0.2/ai-issue_1.0.2_darwin_arm64.tar.gz"
      sha256 "707584e3c44fdd6b15aa665545c84fe927a874b0561f08b06002d9c93ede39fb"

      define_method(:install) do
        bin.install "ai-issue"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/replworks/ai-issue/releases/download/v1.0.2/ai-issue_1.0.2_linux_amd64.tar.gz"
      sha256 "9aa892f3218512a0a12699a2b542221399e7e90c8dc9bd59d6543d58a049e3ed"
      define_method(:install) do
        bin.install "ai-issue"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/replworks/ai-issue/releases/download/v1.0.2/ai-issue_1.0.2_linux_arm64.tar.gz"
      sha256 "0a93b4689c0029740887160fa4c079a84348d9d6bb73080bf7261f08cf20f330"
      define_method(:install) do
        bin.install "ai-issue"
      end
    end
  end
end
