# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AiIssue < Formula
  desc "A CLI tool to publish AI-generated ideas as GitHub Issues, clearly separating AI authorship from human responsibility."
  homepage "https://github.com/replworks/ai-issue"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/replworks/ai-issue/releases/download/v1.1.0/ai-issue_1.1.0_darwin_amd64.tar.gz"
      sha256 "60ad2b117a8b9127c891b66f54e7c841c2cd710068b79c69163adf9426f24ba3"

      define_method(:install) do
        bin.install "ai-issue"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/replworks/ai-issue/releases/download/v1.1.0/ai-issue_1.1.0_darwin_arm64.tar.gz"
      sha256 "27efd7dd39f5f0c0dfe2238435e95be0e223733a20cbb69e2874ec17e4489263"

      define_method(:install) do
        bin.install "ai-issue"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/replworks/ai-issue/releases/download/v1.1.0/ai-issue_1.1.0_linux_amd64.tar.gz"
      sha256 "eb45a4c67f73c5a74fdc86e336eb72c5510ec630462e270ce3108b6dbbc4c55b"
      define_method(:install) do
        bin.install "ai-issue"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/replworks/ai-issue/releases/download/v1.1.0/ai-issue_1.1.0_linux_arm64.tar.gz"
      sha256 "e69a87ad42738e21b323a6fc9e6b9ca763c78345cbc3c9964ae0451f9ae890eb"
      define_method(:install) do
        bin.install "ai-issue"
      end
    end
  end
end
