# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ReplCli < Formula
  desc "A deterministic runtime controller for external AI-driven task execution."
  homepage "https://github.com/replworks/repl-cli"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/replworks/repl-cli/releases/download/v0.1.2/repl-cli_0.1.2_darwin_amd64.tar.gz"
      sha256 "f66cdf5a8aa7d11ec5478783312d7d75589a1db1257022b7ae4a8778182a3e96"

      define_method(:install) do
        bin.install "repl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/replworks/repl-cli/releases/download/v0.1.2/repl-cli_0.1.2_darwin_arm64.tar.gz"
      sha256 "9108a1e4fd4ebf49cd99666ef5820285717a3cb4f89eb51c010161a53436a250"

      define_method(:install) do
        bin.install "repl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/replworks/repl-cli/releases/download/v0.1.2/repl-cli_0.1.2_linux_amd64.tar.gz"
      sha256 "de57a5050844cd06ae25946c62b4e1b90d6e3b0c4405a196cf33daeba7744722"
      define_method(:install) do
        bin.install "repl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/replworks/repl-cli/releases/download/v0.1.2/repl-cli_0.1.2_linux_arm64.tar.gz"
      sha256 "ee5db1e7b0038623e8f38530cb25a02b7280f5fc7fbdfadb1cfdf06c0ea23636"
      define_method(:install) do
        bin.install "repl"
      end
    end
  end
end
