# This file was generated by GoReleaser. DO NOT EDIT.
cask "ai-issue" do
  on_macos do
    postflight_steps do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/ai-issue"]
    end
  end

  version "1.1.1"

  on_macos do
    on_arm do
      sha256 "ac97782618d532cfef02b2ba04590134cee950409b10cb06d930f791246444bc"
      url "https://github.com/replworks/ai-issue/releases/download/v#{version}/ai-issue_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "befff2c9ff86d40f9572ccc8fc6e70086b9607259c9a29ec2326c5ff38d8e768"
      url "https://github.com/replworks/ai-issue/releases/download/v#{version}/ai-issue_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "f033a4a64b584b722b92881d7b6ff2bfb020adbb53bb3ab747e2b9c8e73de38e"
      url "https://github.com/replworks/ai-issue/releases/download/v#{version}/ai-issue_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "a61f3e72435be030764fd5550df2ffb2bf7d4a39de0ca9a211507bc23decf327"
      url "https://github.com/replworks/ai-issue/releases/download/v#{version}/ai-issue_#{version}_linux_amd64.tar.gz"
    end
  end

  name "ai-issue"
  desc "Publish AI-generated ideas as GitHub Issues with publisher traceability"
  homepage "https://github.com/replworks/ai-issue"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ai-issue"

  # No zap stanza required
end
