# This file was generated by GoReleaser. DO NOT EDIT.
cask "ai-issue" do
  on_macos do
    postflight_steps do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/ai-issue"]
    end
  end

  version "1.2.0"

  on_macos do
    on_arm do
      sha256 "54f5eb6d9551dfddf85f81dc866921f421a031a501fff3198ad945316e43ddf0"
      url "https://github.com/replworks/ai-issue/releases/download/v#{version}/ai-issue_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "9fe6bc567e77128c8fe0ba73baaae6d7538090a0dc4bb1f4e5ff97647aef2402"
      url "https://github.com/replworks/ai-issue/releases/download/v#{version}/ai-issue_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "dd8672441accaa091253263f6359d7b4136da94434436dd906a0cdf850702804"
      url "https://github.com/replworks/ai-issue/releases/download/v#{version}/ai-issue_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "21333afac890caa500540d6e473ccfe8721d3f10463335783e8c46543922f470"
      url "https://github.com/replworks/ai-issue/releases/download/v#{version}/ai-issue_#{version}_linux_amd64.tar.gz"
    end
  end

  name "ai-issue"
  desc "Publish AI-generated ideas as GitHub Issues with publisher traceability"
  homepage "https://github.com/replworks/ai-issue"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ai-issue"

  # No zap stanza required
end
