# This file was generated by GoReleaser. DO NOT EDIT.
cask "coolrestore" do
  version "0.1.1"

  on_macos do
    on_arm do
      sha256 "2d1e5e3c57a2d4fa17c17a662867beec7b5c762bfa331bb85d82c7af5eb37399"
      url "https://github.com/replworks/coolrestore/releases/download/v#{version}/coolrestore_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "5076713236bd1c5147e29def8111392e35eaf949c6e7327c9625144b2ddd1a68"
      url "https://github.com/replworks/coolrestore/releases/download/v#{version}/coolrestore_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "8a5a1fa876ecc8fcec5f13baf36bd845c7381274d85993dd910579389b742537"
      url "https://github.com/replworks/coolrestore/releases/download/v#{version}/coolrestore_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "930b03a6c97b96d927af4dd8d9b070b87c650022e7a7983ba211be3ce20fed45"
      url "https://github.com/replworks/coolrestore/releases/download/v#{version}/coolrestore_#{version}_linux_amd64.tar.gz"
    end
  end

  name "coolrestore"
  desc "Safely restore Coolify storage backups from S3-compatible storage after an incident"
  homepage "https://github.com/replworks/coolrestore"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "coolrestore"

  on_macos do
    postflight_steps do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/coolrestore"]
    end
  end

  # No zap stanza required
end
