# This file was generated by GoReleaser. DO NOT EDIT.
cask "coolrestore" do
  on_macos do
    postflight_steps do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/coolrestore"]
    end
  end

  version "1.0.0"

  on_macos do
    on_arm do
      sha256 "bc8cf15b2d1b3d5a9c7e61690331b8f684af73de477fe95b86309b65ff22f043"
      url "https://github.com/replworks/coolrestore/releases/download/v#{version}/coolrestore_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "a035f9eecb4c229f5b7d3ac749361640913906a42debc5baf7cf5745eee44e45"
      url "https://github.com/replworks/coolrestore/releases/download/v#{version}/coolrestore_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "7649c573783eeb063fce46d90026cbcec60750b5d99dc45d672707640e267955"
      url "https://github.com/replworks/coolrestore/releases/download/v#{version}/coolrestore_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "c090e2970aadc3b4e863a5f8c37cf336cceca86f57b8f88ca4e17f3028bae14d"
      url "https://github.com/replworks/coolrestore/releases/download/v#{version}/coolrestore_#{version}_linux_amd64.tar.gz"
    end
  end

  name "coolrestore"
  desc "Safely restore Coolify storage backups from S3-compatible storage after an incident"
  homepage "https://github.com/replworks/coolrestore"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "coolrestore"

  # No zap stanza required
end
