# This file was generated by GoReleaser. DO NOT EDIT.
cask "coolrestore" do
  on_macos do
    postflight_steps do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/coolrestore"]
    end
  end

  version "1.1.0"

  on_macos do
    on_arm do
      sha256 "74625a2773c2a05958fe0bc08611dac8d1f6cf3ed3813aecbeb8b4a0bbce9d98"
      url "https://github.com/replworks/coolrestore/releases/download/v#{version}/coolrestore_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "776ccd187432e33aa502ff7e504de0c80a3750606c79e357e64f785c3ef2400e"
      url "https://github.com/replworks/coolrestore/releases/download/v#{version}/coolrestore_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "306b131352444dad02d7fa803629c0663bbc3d5805ebcf1c7b4a8cc8efa06933"
      url "https://github.com/replworks/coolrestore/releases/download/v#{version}/coolrestore_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "6f5d72f040f884a09e75ddd49a2cbe26da879fc14a1e74d3c6daf3702972c057"
      url "https://github.com/replworks/coolrestore/releases/download/v#{version}/coolrestore_#{version}_linux_amd64.tar.gz"
    end
  end

  name "coolrestore"
  desc "Safely restore Coolify storage backups from S3-compatible storage after an incident"
  homepage "https://github.com/replworks/coolrestore"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "coolrestore"

  # No zap stanza required
end
