# This file was generated by GoReleaser. DO NOT EDIT.
cask "repl-cli" do
  version "0.1.3"

  on_macos do
    on_arm do
      sha256 "4d6769b3d12a0de57d7ddefadedfa76e00addf7ee0ded9821d97c9516b140fe9"
      url "https://github.com/replworks/repl-cli/releases/download/v#{version}/repl-cli_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "2a09bd6ada18bd685ed34a20b96d096d0b1403e8b912a370b67757901d1ac0ce"
      url "https://github.com/replworks/repl-cli/releases/download/v#{version}/repl-cli_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "d5a790dd4eba51128b4616cdfa8f4396c4855e5b1e2c6028d6e0824778cb8d02"
      url "https://github.com/replworks/repl-cli/releases/download/v#{version}/repl-cli_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "e57b9e5566805e58487460e4037d33df9589222f57d936f84f2ed6f3cc4241e1"
      url "https://github.com/replworks/repl-cli/releases/download/v#{version}/repl-cli_#{version}_linux_amd64.tar.gz"
    end
  end

  name "repl-cli"
  desc "A deterministic runtime controller for external AI-driven task execution."
  homepage "https://github.com/replworks/repl-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "repl-cli"

  on_macos do
    postflight_steps do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/coolrestore"]
    end
  end

  # No zap stanza required
end
